<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Inertia.Core" Version="0.1.1" />
    <PackageReference Include="Inertia.React" Version="0.1.1" />
  </ItemGroup>

</Project>
